# Generated by Django 5.0.4 on 2024-04-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Адрес')),
            ],
            options={
                'verbose_name': 'Корт',
                'verbose_name_plural': 'Корты',
            },
        ),
    ]
