"""Initial

Revision ID: 63755bdf13ce
Revises: 
Create Date: 2024-01-30 09:56:46.341008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63755bdf13ce'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('NTRP', sa.Float(), nullable=False),
    sa.Column('tg_id', sa.Integer(), nullable=False),
    sa.Column('user_name_tg', sa.String(), nullable=False),
    sa.Column('games_played_on_week', sa.Integer(), nullable=False),
    sa.Column('is_notification', sa.Boolean(), nullable=False),
    sa.Column('is_notification_changes', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id'),
    sa.UniqueConstraint('user_name_tg')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('players')
    # ### end Alembic commands ###
