# Generated by Django 5.0.4 on 2024-04-19 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('rank', models.CharField(blank=True, max_length=4, null=True, verbose_name='NTRP-рейтинг')),
                ('tg_id', models.CharField(max_length=100, verbose_name='ID в Telegram')),
                ('tg_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ник в Telegram')),
                ('is_notify_about_games', models.BooleanField(default=False, verbose_name='Уведомлять о играх')),
                ('is_notify_about_changes', models.BooleanField(default=False, verbose_name='Уведомлять о изменениях')),
            ],
        ),
    ]
